import Head from "next/head";
import PostList from "../components/PostList";
import PostHead from "../components/PostHead";
import PostPhoto from "../components/PostPhoto";
import Navbar from "../components/Navbar";
import DetailPost from "../components/DetailPost";

export default function Detail() {
  return (
    <div>
      <Head>
        <title>Fast News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <div className=" bg-primary">
        <div className="container  mx-auto">
          <Navbar />
        </div>
      </div>
      {/* Navbar END */}

      {/* Main */}
      <div className="flex p-10">
        <div className="container flex-initial w-1/4  p-3 bg-secondary rounded-md">
          <PostList />
        </div>
        <div className="container flex-initial w-5/6 mx-5 p-3 bg-secondary rounded-md">
          <DetailPost />
        </div>
        <div className="container flex-initial w-1/4  p-3 bg-secondary rounded-md">
          <PostPhoto />
        </div>
      </div>
      {/* Main END */}
    </div>
  );
}
