import Image from "next/image";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import { PostCard, PostWidget, Categories } from "../components";
import PostDetail from "../components/PostDetail";
import PostList from "../components/PostList";
import PostHead from "../components/PostHead";
import PostPhoto from "../components/PostPhoto";
import Navbar from "../components/Navbar";
// import { PostList, PostHead, PostPhoto, Navbar } from "../components";

const posts = [
  { title: "React Testing", excerpt: "Learn React Testing" },
  { title: "React With Tailwind", excerpt: "Learn React With Tailwind" },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fast News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="container mx-auto px-10 mb-5 bg-slate-400">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          <div className="lg:col-span-8 col-span-1">
            {posts.map((post, index) => (
              <PostCard post={post} key={post.title} />
            ))}
          </div>

          <div className="lg:col-span-4 col-span-1">
            <div className="lg:sticky relative top-8">
              <PostWidget />
              <Categories />
            </div>
          </div>
        </div>
      </div> */}

      {/* Navbar */}
      <div className=" bg-blue-600">
        <div className="container  mx-auto">
          <Navbar />
        </div>
      </div>
      {/* Navbar END */}

      {/* Main */}
      <div className="flex p-10">
        <div className="container flex-initial w-1/4  p-3 bg-gray-200 rounded-md">
          <PostList />
        </div>
        <div className="container flex-initial w-5/6 mx-5 p-3 bg-gray-200 rounded-md">
          <PostHead />
        </div>
        <div className="container flex-initial w-1/4  p-3 bg-gray-200 rounded-md">
          <PostPhoto />
        </div>
      </div>
      {/* Main END */}
    </div>
  );
}
